#!/usr/bin/env bash
# Seeds the user-level leak-guard pattern file (tier 2 of
# .githooks/leak-guard.sh) with literals derivable from this machine:
# sibling project directory names, hostname, and username. Non-derivable
# literals (fleet codenames, LAN IPs, internal hostnames) must be added by
# hand afterwards - the generated file says so.
#
# Runs from the package.json `prepare` script. Exits silently if the file
# already exists; never overwrites. The generated file lives outside the
# repo and must never be committed.
#
# Keep this file byte-identical between the aidd, spernakit, and starsync repos.
set -euo pipefail

target="${LEAK_GUARD_PATTERNS:-$HOME/.config/leak-guard/patterns}"
[ -f "$target" ] && exit 0

# Names that are public (or dot-dirs) and must not become private literals.
is_public() {
	case "$1" in
	aidd | spernakit | starsync | node_modules | .*) return 0 ;;
	esac
	return 1
}

escape_ere() {
	printf '%s' "$1" | sed 's/[][\.|$(){}?+*^]/\\&/g'
}

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
workspace="$(dirname "$repo_root")"

mkdir -p "$(dirname "$target")"
{
	echo '# leak-guard private patterns (extended regex, one per line; # = comment).'
	echo '# Tier 2 of .githooks/leak-guard.sh - never commit this file.'
	echo '# Generated by .githooks/leak-guard-setup.sh from workspace directory'
	echo '# names, hostname, and username. REVIEW IT and add non-derivable'
	echo '# literals by hand: fleet codenames, LAN IPs, internal hostnames.'
	for dir in "$workspace"/*/; do
		[ -d "$dir" ] || continue
		name="$(basename "$dir")"
		is_public "$name" && continue
		# Very short names (ai, g5, ...) collide with ordinary prose; add
		# them by hand only if they are genuinely private.
		[ "${#name}" -lt 4 ] && continue
		printf '\\b%s\\b\n' "$(escape_ere "$name")"
	done
	host="$(hostname 2>/dev/null || true)"
	if [ -n "$host" ]; then
		printf '\\b%s\\b\n' "$(escape_ere "$host")"
	fi
	user_name="${USERNAME:-${USER:-}}"
	if [ -n "$user_name" ]; then
		printf '\\b%s\\b\n' "$(escape_ere "$user_name")"
	fi
} >"$target"

echo "leak-guard: generated $target - review it and add fleet codenames / LAN IPs." >&2
exit 0
